sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPvKrZLmNtKGYjR8Wtg
    access-key-secret: vI0IfYwG9Xej1l8hw8zm0Z0hvCm3qQ
    bucket-name: typorabed-lpl
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxd78b138ffc3d39e8
    secret: c8f2283f950b3a16e7b98789e3e286dc